param(
    [string]$Root = ".",
    [string]$OutputPath = "docs/indexes/incomplete-docs.md",
    [string]$Owner = "Michael"
)

$ErrorActionPreference = "Stop"

$targetStatuses = @("Draft", "Needs Review")
$utf8BomChar    = [char]0xFEFF
$metadataPattern = '^<sub><(?:em|i)>\s*Status:\s*(?<Status>[^|]+?)\s*\|\s*Audience:\s*(?<Audience>[^|]+?)\s*\|\s*Doc-Type:\s*(?<DocType>[^|]+?)\s*\|\s*Owner:\s*(?<Owner>[^|]+?)\s*\|\s*Last Reviewed:\s*(?<LastReviewed>[^|]+?)\s*\|\s*Canonical:\s*(?<Canonical>[^|<]+?)\s*</(?:em|i)></sub>$'

function Parse-Metadata {
    param([string]$Line)
    $clean = $Line.TrimStart($utf8BomChar)
    if ($clean -notmatch $metadataPattern) { return $null }
    return @{
        Status       = $Matches['Status'].Trim()
        Audience     = $Matches['Audience'].Trim()
        DocType      = $Matches['DocType'].Trim()
        Owner        = $Matches['Owner'].Trim()
        LastReviewed = $Matches['LastReviewed'].Trim()
        Canonical    = $Matches['Canonical'].Trim()
    }
}

function Get-DocTitle {
    param([string[]]$Lines)
    foreach ($line in $Lines) {
        if ($line -match '^#+\s+(.+)$') {
            return $Matches[1].Trim()
        }
    }
    return "(untitled)"
}

function Get-RelLink {
    param([string]$FromDir, [string]$ToFile)
    $fromUri = [System.Uri]::new(
        [System.IO.Path]::GetFullPath($FromDir).TrimEnd([System.IO.Path]::DirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
    )
    $toUri = [System.Uri]::new([System.IO.Path]::GetFullPath($ToFile))
    return $fromUri.MakeRelativeUri($toUri).ToString() -replace '%20', ' '
}

# ── Resolve paths ────────────────────────────────────────────────────────────

$rootPath       = (Resolve-Path -LiteralPath $Root).ProviderPath
$outputFullPath = [System.IO.Path]::GetFullPath((Join-Path $rootPath $OutputPath))
$outputDir      = Split-Path $outputFullPath -Parent
$rootUri        = [System.Uri]::new($rootPath.TrimEnd([System.IO.Path]::DirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar)

# ── Scan markdown files ───────────────────────────────────────────────────────

$markdownFiles = Get-ChildItem -Path $rootPath -Recurse -File -Filter *.md |
    Where-Object {
        $_.FullName -notmatch "[\\/]\.git[\\/]" -and
        $_.FullName -ne $outputFullPath
    } |
    Sort-Object FullName

$buckets = [ordered]@{}
foreach ($s in $targetStatuses) {
    $buckets[$s] = [System.Collections.Generic.List[pscustomobject]]::new()
}

foreach ($file in $markdownFiles) {
    $lines = Get-Content -Path $file.FullName -Encoding UTF8 -ErrorAction SilentlyContinue
    if (-not $lines -or $lines.Count -lt 1) { continue }

    $meta = Parse-Metadata -Line $lines[0]
    if (-not $meta -or $targetStatuses -notcontains $meta.Status) { continue }

    $displayPath = $rootUri.MakeRelativeUri([System.Uri]::new($file.FullName)).ToString() -replace '%20', ' '
    $relLink     = Get-RelLink -FromDir $outputDir -ToFile $file.FullName
    $title       = Get-DocTitle -Lines $lines

    $buckets[$meta.Status].Add([pscustomobject]@{
        DisplayPath  = $displayPath
        RelLink      = $relLink
        Title        = $title
        Audience     = $meta.Audience
        DocType      = $meta.DocType
        LastReviewed = $meta.LastReviewed
    })
}

# ── Build output ──────────────────────────────────────────────────────────────

$today      = (Get-Date).ToString("yyyy-MM-dd")
$totalCount = ($buckets.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum

$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add("<sub><em>Status: Active | Audience: Internal | Doc-Type: Workflow | Owner: $Owner | Last Reviewed: $today | Canonical: Yes</em></sub>")
$lines.Add("")
$lines.Add("# Incomplete Docs Index")
$lines.Add("")
$lines.Add("_Auto-generated by ``scripts/generate-incomplete-index.ps1``. Do not edit by hand - this file is overwritten on every push to main._")
$lines.Add("")
$lines.Add("Lists all documents whose status is ``Draft`` or ``Needs Review``. These files need attention before they can be treated as reliable.")
$lines.Add("")

if ($totalCount -eq 0) {
    $lines.Add("**All docs are Active or Archived - nothing needs attention right now.**")
} else {
    $lines.Add("**$totalCount file(s) need attention.**")
}

$statusDescriptions = @{
    "Draft"        = "Incomplete or planned content - not yet authoritative."
    "Needs Review" = "Content exists but must be validated before relying on it."

}

foreach ($status in $targetStatuses) {
    $entries = $buckets[$status]
    $lines.Add("")
    $lines.Add("## $status")
    $lines.Add("")
    $lines.Add($statusDescriptions[$status])
    $lines.Add("")

    if ($entries.Count -eq 0) {
        $lines.Add("_No files currently have this status._")
    } else {
        $lines.Add("| Doc | Title | Audience | Doc Type | Last Reviewed |")
        $lines.Add("| --- | ----- | -------- | -------- | ------------- |")
        foreach ($entry in ($entries | Sort-Object DisplayPath)) {
            $lines.Add("| [$($entry.DisplayPath)]($($entry.RelLink)) | $($entry.Title) | $($entry.Audience) | $($entry.DocType) | $($entry.LastReviewed) |")
        }
    }
}

# ── Write file (UTF-8, no BOM) ────────────────────────────────────────────────

if (-not (Test-Path -LiteralPath $outputDir -PathType Container)) {
    New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
}

$content = ($lines -join "`n") + "`n"
[System.IO.File]::WriteAllText($outputFullPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated '$OutputPath' with $totalCount incomplete file(s) ($($buckets['Draft'].Count) Draft, $($buckets['Needs Review'].Count) Needs Review)."
